const i18Obj = {
  en: {
    backquote: '`',
    q: 'q',
    w: 'w',
    e: 'e',
    r: 'r',
    t: 't',
    y: 'y',
    u: 'u',
    i: 'i',
    o: 'o',
    p: 'p',
    '[': '[',
    ']': ']',
    a: 'a',
    s: 's',
    d: 'd',
    f: 'f',
    g: 'g',
    h: 'h',
    j: 'j',
    k: 'k',
    l: 'l',
    ';': ';',
    quotes: "'",
    z: 'z',
    x: 'x',
    c: 'c',
    v: 'v',
    b: 'b',
    n: 'n',
    m: 'm',
    comma: ',',
    period: '.',
    slash: '/',
    system: 'keyboard created in windows system',
    changing: 'for changing language: ctrl + alt',
  },
  ru: {
    backquote: 'ё',
    q: 'й',
    w: 'ц',
    e: 'у',
    r: 'к',
    t: 'е',
    y: 'н',
    u: 'г',
    i: 'ш',
    o: 'щ',
    p: 'з',
    '[': 'х',
    ']': 'ъ',
    a: 'ф',
    s: 'ы',
    d: 'в',
    f: 'а',
    g: 'п',
    h: 'р',
    j: 'о',
    k: 'л',
    l: 'д',
    ';': 'ж',
    quotes: 'э',
    z: 'я',
    x: 'ч',
    c: 'с',
    v: 'м',
    b: 'и',
    n: 'т',
    m: 'ь',
    comma: 'б',
    period: 'ю',
    slash: '.',
    system: 'клавиатура создана в операционной системе windows',
    changing: 'для переключения языка: ctrl + alt',
  },
};
export default i18Obj;
